#!/bin/sh
if [ -z $1 ]; then
    echo "argv1 : folder"
    exit
elif [ -z $2 ]; then
    echo "argv2 : version"
    exit
fi

FOLDER="$1"
VERSION="$2"

VERSION_IN_FOLDER=`cat $FOLDER/VERSION`

if [ $? -ne 0 ]; then
    echo "Maybe, You should check folder!"
    exit
fi

if [ ${VERSION_IN_FOLDER:0:6} = "go$VERSION" ]; then
    sudo rm /usr/lib/go
    sudo rm -r /usr/lib/go-$VERSION

    sudo cp -r $FOLDER /usr/lib/go-$VERSION
    cd /usr/lib
    sudo ln -s go-$VERSION go
    sudo rm /usr/bin/go
    sudo rm /usr/bin/gofmt
    sudo ln -s ../lib/go-$VERSION/bin/go /usr/bin/go
    sudo ln -s ../lib/go-$VERSION/bin/gofmt /usr/bin/gofmt
	go version
else
    echo "Maybe, You should check version!"
fi
