alias py=python
alias lh="ls -lh"
alias lha="ls -lha"
alias llh="ls -lha"
alias na="nautilus . &"
alias cdgithub="cd $HOME/github"
alias cdkhpark0203="cd $HOME/github/khpark0203"
alias cdmydev="cd $HOME/github/khpark0203/mydev"
alias gcc="gcc -no-pie"
alias ll="ls -l"
alias lla="ls -la"
alias ga="gitahead . &"
alias make=/usr/bin/colormake
alias omake=/usr/bin/make
alias mlist="xfreerdp /monitor-list"
alias xc="sed -z '$ s/\n$//' | xclip -selection clipboard"
alias dk=docker
alias key="$HOME/.key.sh"
alias dns="sudo systemctl restart systemd-resolved.service"
alias remove-sni="sudo iptables -A INPUT -p tcp --tcp-flags RST RST --sport 443 -j DROP"
alias k=kubectl
alias kc=kubectl
alias ku=kubectl
alias exnodeoptions="export NODE_OPTIONS='--openssl-legacy-provider'"
alias audio-hdmi="pacmd set-card-profile 0 output:hdmi-stereo+input:analog-stereo"
alias audio-laptop="pacmd set-card-profile 0 output:analog-stereo+input:analog-stereo"
alias b="git branch"
alias p="git pull"
alias s="git status"
alias mk=minikube
alias ga="gitahead &"
alias gk=rabbitvcs
alias tp=typora
