#!/bin/sh

monitor_num=`xfreerdp /monitor-list | wc -l`

if [ $monitor_num -ge 3 ]; then
	if [ -z $1 ]; then
		echo "fill in monitor's number (ex. hae 0,1)"
		xfreerdp /monitor-list
		exit
	else
		monitor="/monitors:$1"
	fi
else
	monitor=$@
fi

#xfreerdp /home/khpark0203/Downloads/hae.rdp /d:HKMC /u:E156786 /p:Rhksgh1272\!\@ /smart-sizing /audio-mode:mode /floatbar:show:always,sticky:off,default:visible +auto-reconnect /auto-reconnect-max-retries:10 +clipboard /rfx /gfx /compression /compression-level:2 /multimon $monitor
xfreerdp /v:10.40.105.177 /d:HKMC /u:E156786 /p:Rhksgh1272\! /smart-sizing /microphone /audio-mode:mode /floatbar:show:always,sticky:off,default:visible +auto-reconnect /auto-reconnect-max-retries:10 /rfx /gfx /compression /compression-level:2 +window-drag +clipboard +menu-anims /multimon $monitor
