#!/bin/sh

current=`pactl get-default-sink`

if [ $current = "alsa_output.pci-0000_00_1f.3.analog-stereo" ]; then
    pacmd set-card-profile 0 output:hdmi-stereo+input:analog-stereo
else
    pacmd set-card-profile 0 output:analog-stereo+input:analog-stereo
fi
